apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: competex-db
  namespace: competex-db  # Make sure the namespace exists
spec:
  serviceName: "competex-db"
  replicas: 1  # Adjust the number of replicas based on your needs
  selector:
    matchLabels:
      app: competex-db
  template:
    metadata:
      labels:
        app: competex-db
    spec:
      containers:
      - name: competex-db
        image: postgres:latest # ilum1/competex:master_db  # Replace with actual Docker Hub path
        ports:
        - containerPort: 5432
          name: db
        env:
        - name: POSTGRES_USER
          value: postgres  # It's better to use a Secret for this
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: competex-db-secret  # Referencing the Secret
              key: password
        - name: POSTGRES_DB
          value: competexdb
        - name: DB_HOST
          value: competex-db-headless-service
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/postgresql/data
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d/init.sql
          subPath: init.sql
      volumes:
      - name: init-scripts
        configMap:
          name: competex-db-config
  volumeClaimTemplates:
  - metadata:
      name: db-storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
