apiVersion: v1
kind: Service
metadata:
  name: competex-db-nodeport
  namespace: competex-db
spec:
  type: NodePort
  #selector:
    #app: competex-db
  ports:
    - name: db
      port: 5432
      targetPort: 5432
      nodePort: 30003  # Choose an available node port within the range (30000-32767)
