apiVersion: v1
kind: PersistentVolume
metadata:
  name: competex-db-pv
  namespace: competex-db
  labels:
    type: local
    app: competex-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql