apiVersion: v1
kind: Service
metadata:
  name: competex-db-headless-service
  namespace: competex-db
spec:
  clusterIP: None
  selector:
    app: competex-db # Label selector that matches StatefulSet
  ports:
  - name: db
    port: 5432
    targetPort: 5432